#include <bits/stdc++.h>
using namespace std;


void solve(long long N){
  long long sum = 0;
  for (long long i=1; i<=N; i++) if (i%3 != 0 && i%5 != 0) sum += i;
  cout << sum << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    solve(N);
    return 0;
}
