#include <bits/stdc++.h>
using namespace std;


void solve(long long K, long long N, std::vector<long long> A){
  vector<int> vec = {};
  long long first = (K - A[A.size()-1]) + A[0];
  vec.push_back(first);

  for (int i=0; i<A.size()-1; i++) {
    long long distance = A[i+1] - A[i];
    vec.push_back(distance);
  }
  cout << K - *max_element(vec.begin(), vec.end()) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    scanf("%lld",&K);
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(K, N, std::move(A));
    return 0;
}
