#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
  string n;
  int sum = 0;
  cin >> n;
  for (int i=0; i<n.size(); i++) {
    sum += n[i] - '0';
  }

  auto result = (stoi(n) % sum == 0) ? YES : NO;
  cout << result << endl;
}
