#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long M, std::vector<std::string> S, std::vector<long long> C){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<std::string> S(M);
    std::vector<long long> C(M);
    for(int i = 0 ; i < M ; i++){
        std::cin >> S[i];
        scanf("%lld",&C[i]);
    }
    solve(N, M, std::move(S), std::move(C));
    return 0;
}
