[package]
name = "bitonic-sorter"
version = "0.1.0"
authors = ["nixiesquid <audu817@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
rand_pcg = "0.2.0"
rayon = "1.2.0"
num_cpus = "1.10.1"