#include <bits/stdc++.h>
using namespace std;


void solve(long long W, long long H, long long K){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long W;
    scanf("%lld",&W);
    long long H;
    scanf("%lld",&H);
    long long K;
    scanf("%lld",&K);
    solve(W, H, K);
    return 0;
}
