#include <bits/stdc++.h>
#define ALL(v) (v).begin(),(v).end()
using namespace std;
using LL = long long;

void solve(long long N, std::vector<long long> A){
  LL to = -1;
  LL from = -1;
  map<int, int> mp;
  for (unsigned int i=0; i<A.size(); i++) mp[i+1] = 0;
  sort(ALL(A));
  for (int i : A) mp[i]++;
  for (auto val : mp) {
    if (val.second == 2) to = val.first;
    if (val.second == 0) from = val.first;
  }

  if (to == -1) cout << "Correct" << endl;
  else cout << to << ' ' << from << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld", &N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
