#include <bits/stdc++.h>
using namespace std;


void solve(long long X){
  long long score = 0;
  while (500 <= X) {
    X -= 500;
    score += 1000;
  }

  while (5 <= X) {
    X -= 5;
    score += 5;
  }
  cout << score << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long X;
    scanf("%lld",&X);
    solve(X);
    return 0;
}
