#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long W, long long C, std::vector<long long> l, std::vector<long long> r, std::vector<long long> p){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long W;
    scanf("%lld",&W);
    long long C;
    scanf("%lld",&C);
    std::vector<long long> l(N);
    std::vector<long long> r(N);
    std::vector<long long> p(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&l[i]);
        scanf("%lld",&r[i]);
        scanf("%lld",&p[i]);
    }
    solve(N, W, C, std::move(l), std::move(r), std::move(p));
    return 0;
}
