#include <bits/stdc++.h>
using namespace std;


void solve(long long S){
  string str = to_string(S);
  vector<string> vec;
  long long ans = 0;

  // scan all bit pattern
  for (int s = 0; s < (1 << (str.size()-1)); s++) {
    string now = "";
    now += str[0];
    // scan which bit is valid or not
    for (int plus = 0; plus < str.size() - 1; plus++) {
      if (s & (1 << plus)) now += "+";
      now += str[plus + 1];
    }
    
    // calcurate
    long long sum = 0;
    int pos = 0;
    while (now.find("+", pos) != string::npos) {
      int nextpos = now.find("+", pos);
      sum += stoll(now.substr(pos, nextpos - pos));
      pos = nextpos + 1;
    }
    sum += stoll(now.substr(pos));
    ans += sum;
  }
  cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
  long long S;
  scanf("%lld",&S);
  solve(S);
  return 0;
}
