#include <bits/stdc++.h>
using namespace std;


void solve(long long K, long long A, long long B){
  bool flag = false;
  for (int i=A; i<=B; i++) if (i % K == 0) flag = true;
  string ans = (flag) ? "OK" : "NG";
  cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    scanf("%lld",&K);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    solve(K, A, B);
    return 0;
}
