#include <bits/stdc++.h>
using namespace std;


map<int, int> m{};
void solve(long long N, std::vector<long long> A){
  int get_nums = N / 2;
  for (int i=0; i<N; i++) m[A[i]] = i;
  sort(A.rbegin(), A.rend());

  while (get_nums > 0) {
    // TODO: 先頭から順にindexに気をつけつつ採用したところで、それが本当に最大値であるという保証はない(先頭から2番目を筆頭に採用したほうが最大値、という可能性もあるので。)
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
