#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long M, std::vector<long long> x, std::vector<long long> y, std::vector<long long> c, std::vector<long long> X, std::vector<long long> Y, std::vector<long long> C){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> x(N);
    std::vector<long long> y(N);
    std::vector<long long> c(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&x[i]);
        scanf("%lld",&y[i]);
        scanf("%lld",&c[i]);
    }
    std::vector<long long> X(M);
    std::vector<long long> Y(M);
    std::vector<long long> C(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&X[i]);
        scanf("%lld",&Y[i]);
        scanf("%lld",&C[i]);
    }
    solve(N, M, std::move(x), std::move(y), std::move(c), std::move(X), std::move(Y), std::move(C));
    return 0;
}
