#include <bits/stdc++.h>
using namespace std;


string solve(long long N, long long Y){
    for (int i = 0; i <= N; i++) {
        for (int j = 0; (i + j) <= N; j++) {
            int k = N - (i + j);
            if (1'000 * i + 5'000 * j + 10'000 * k == Y) {
                return to_string(k) + " " + to_string(j) + " " + to_string(i);
            }
        }
    }
    return "-1 -1 -1";
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long Y;
    scanf("%lld",&Y);
    string ans = solve(N, Y);
    cout << ans << endl;
    return 0;
}
