#include <bits/stdc++.h>
using namespace std;


void solve(long long a_I, long long a_O, long long a_T, long long a_J, long long a_L, long long a_S, long long a_Z){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a_I;
    scanf("%lld",&a_I);
    long long a_O;
    scanf("%lld",&a_O);
    long long a_T;
    scanf("%lld",&a_T);
    long long a_J;
    scanf("%lld",&a_J);
    long long a_L;
    scanf("%lld",&a_L);
    long long a_S;
    scanf("%lld",&a_S);
    long long a_Z;
    scanf("%lld",&a_Z);
    solve(a_I, a_O, a_T, a_J, a_L, a_S, a_Z);
    return 0;
}
