#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long K, std::vector<long long> l){
    sort(l.begin(), l.end(), [](long long x, long long y){ return x > y; });
    int ans = 0;
    for (int i = 0; i < K; i++) ans += l[i];
    cout << ans << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> l(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&l[i]);
    }
    solve(N, K, std::move(l));
    return 0;
}
