#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long L, std::vector<long long> x, std::vector<long long> T){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long L;
    scanf("%lld",&L);
    std::vector<long long> x(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&x[i]);
    }
    std::vector<long long> T(3);
    for(int i = 0 ; i < 3 ; i++){
        scanf("%lld",&T[i]);
    }
    solve(N, L, std::move(x), std::move(T));
    return 0;
}
