#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string S){
  int score = 0;
  for (int i=0; i<N-2; i++) {
    for (int j=i+1; j<N-1; j++) {
      for (int k=j+1; k<N; k++) {
        if (j-i == k-j) continue;
        if (S[i] != S[j] && S[i] != S[k] && S[j] != S[k]) score++;
      }
    }
  }
  cout << score << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}

