#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long K){
  long long a = A;
  long long b = B;

  if (K <= A) {
    a = A - K;
  } else if (K <= A + B) {
    a = 0;
    b -= K - A;
  } else {
    a = 0; b = 0;
  };
  cout << a << ' ' << b << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long K;
    scanf("%lld",&K);
    solve(A, B, K);
    return 0;
}
